### ISSUE TITLE
SASS /SCSS work on PHP with vs code and how please help me

### ISSUE THREAD

**Issue by Ged007** [TheRealSyler/vscode-sass-indented#100]
SASS /SCSS work on PHP with vs code and how please help me

i open my xampp and start appache and mysql , then i created index.php file and start html codes to centralize and give a page design i use style.scss and connected but it won't edit 

my link was on auto-created by scss - style.css
![Capture](https://user-images.githubusercontent.com/52948198/178005321-2c838f9c-25f7-43cf-b157-fb75bc8fcf08.PNG)

![Capture](https://user-images.githubusercontent.com/52948198/178005103-46fd3717-1c51-45f6-bd93-914c977bc6c4.PNG)

**Comment by TheRealSyler** [comment]
This extension is for `.sass` files only, please open your issue in the vscode repo.
