### ISSUE TITLE
Unexpected indent on enter

### ISSUE THREAD

**Issue by pikeas** [TheRealSyler/vscode-sass-indented#103]
**Describe the bug**
```
foo
    property: value
|<-- place cursor here
```
Pressing enter triggers an indent, resulting in:

```
foo
    property: value

    |<-- cursor moves here
```

**Expected behavior**
```
foo
    property: value

|<-- cursor should move here
```

**Comment by TheRealSyler** [comment]
There is a option to disable this behavior `sass.disableAutoIndent`, you need to reload/restart vscode after changing it.
