### ISSUE TITLE
A very ANNOYING THING

### ISSUE THREAD

**Issue by OreotheCookie** [TheRealSyler/vscode-sass-indented#104]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

**Describe the bug**

**To Reproduce**

The bug  is that there are not values appearing. For Ex in color: blue ; blue wont be recognized. I liked the old sass better. The new update SUCKS!
**Expected behavior**

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

**Additional context**

**Comment by TheRealSyler** [comment]
well that sucks for you, im kinda busy rn, but you can fix it if you want to, i believe in you, buddy.

**Comment by OreotheCookie** [comment]
> well that sucks for you, im kinda busy rn, but you can fix it if you want to, i believe in you, buddy.

Yeah buddy how do I do that

But seriously, just make .sass a copy of .scss

**Comment by TheRealSyler** [comment]
for this extension you need to update https://github.com/TheRealSyler/vscode-sass-indented/blob/master/src/languageFeatures/color/color.provider.ts to include all color words like `red`.
