### ISSUE TITLE
Make Sass just like scss

### ISSUE THREAD

**Issue by OreotheCookie** [TheRealSyler/vscode-sass-indented#105]
The title says it all. Never change .scss and make .sass just like .scss
**Additional context**

**Comment by TheRealSyler** [comment]
im not sure what you want, please elaborate.

**Comment by OreotheCookie** [comment]
> im not sure what you want, please elaborate.

I mean, please just steal all the .scss source code (it's probably open source) and then put it in .sass.

**Comment by TheRealSyler** [comment]
feel free to make a pr, im not going to do that.

**Comment by OreotheCookie** [comment]
Alright mate
