### ISSUE TITLE
How does the magic comment work

### ISSUE THREAD

**Issue by Shane-Peterson** [TheRealSyler/vscode-sass-indented#108]
> if you want to only import the css variables, you can easily do that by using a magic comment //import css-variables from <File Path>.

How does it work, can you give an example? 

Thank you so much!!

**Comment by TheRealSyler** [comment]
lets say you have file `a.sass` and file `b/b.sass`

`a.sass`
```sass
body
  --var: 200px
```

`b/b.sass`
```sass
//import css-variables from ../a


.class 
  margin: var(--var)
```

you should get autocompletion in the `var()` with the variables declared in `a.sass`, im not sure if it works with sass variables.

**Comment by TheRealSyler** [comment]
i think for sass variable you need to use the `@import/@use` but it im not sure if it still works.
