### ISSUE TITLE
Autocomplete not working in Vue

### ISSUE THREAD

**Issue by SpectralKH** [TheRealSyler/vscode-sass-indented#11]
Autocomplete was supposedly added for Vue files in 1.6.1, but it does not seem to be working for me (only syntax highlighting).

As shown in the image, no autocomplete in .vue files inside the <style> tag:
![image](https://user-images.githubusercontent.com/11315492/63601571-f7e94580-c5c5-11e9-9eae-9113c1b16600.png)

**Comment by TheRealSyler** [comment]
@SpectralKH  I'm not at home, so I can't fix it Right now but I looked at the code that adds the completion's and I already know why it doesn't work, for now you have to use double quotes, because I checked for `lang="sass"`, small mistake will definitely be fixed In the next version.

**Comment by SpectralKH** [comment]
@TheRealSyler Ah, I see, I can work with that :) Thanks for the quick response!
