### ISSUE TITLE
Suggestions based on workspace files even when not editing file in workspace

### ISSUE THREAD

**Issue by justinkruit** [TheRealSyler/vscode-sass-indented#112]
**Is your feature request related to a problem? Please describe.**
For a while now, suggestions only work when you edit a scss file inside your workspace. But when you open a file that isn't in your workspace, but with the workspace still open, it stops suggesting stuff. This is not consistent with other languages like PHP. I often work with files remotely, but have a copy of a dev environment open for suggestions.

**Describe the solution you'd like**
When having a workspace open, keep the suggestions working when editing a file that is not in the workspace.

**Describe alternatives you've considered**
As this is the only proper Sass extension, I couldn't find any alternatives. Unfortunately the option to work local only is often not available.

**Comment by TheRealSyler** [comment]
@justinkruit this extension is only for `.sass` consider creating an issue in the vscode repo where the builtin extension should be.
