### ISSUE TITLE
Code assistance is not complete

### ISSUE THREAD

**Issue by Profesor08** [TheRealSyler/vscode-sass-indented#115]
**Describe the bug**
Code assistance is not complete. For some properties it shows all available values, for some just half, for some nothing.

**To Reproduce**
1. Create new ot open existing `.scss` file with some styles.
2. Toggle suggestions for `white-space` property, there will be no one useful.
3. Toggle suggestions for `align-items` property, there will be just some incomplete list of values, no  `start`, `end`, etc related to grids.
4. Toggle suggestions for `overflow` property, there will be all properties available.

**Expected behavior**
To see all available values for property.

**Screenshots**

1. There is OK
![image](https://user-images.githubusercontent.com/8218016/205074200-6b4b5e44-1ea2-42db-ac41-7f82ec102263.png)

2. There is half. Expect to see `start`, `end`, etc in list.
![image](https://user-images.githubusercontent.com/8218016/205074416-2f371f73-e4ca-4f5e-96d3-f78041bb9f0d.png)

3. There is nothing useful
![image](https://user-images.githubusercontent.com/8218016/205075503-7d2242e6-3ab2-4b85-aec5-084ce1f609a9.png)

**Additional context**
May be some dictionary, where are listed all properties with their values, isn't complete or broken.

**Comment by TheRealSyler** [comment]
this extension is for `.sass` only, `.scss` files are handled by a built in extension please open you issue in the vscode repo.

**Comment by Profesor08** [comment]
Changed file extension to `.sass`, and there is no autocomplete at all.
![image](https://user-images.githubusercontent.com/8218016/205096988-79279822-c7f3-4133-9941-437ae30e0a8d.png)

**Comment by TheRealSyler** [comment]
@Profesor08 i updated the data, some properties might have better completion now, but im pretty sure that the `scss` extension uses the same data source (npm @vscode/web-custom-data)
