### ISSUE TITLE
 sass compiler don't appear on the navbar vs code bottom "Watch  Sass" . 

### ISSUE THREAD

**Issue by Anjeli-art** [TheRealSyler/vscode-sass-indented#118]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

**Describe the bug**
the extension sass compiler don't appear on the navbar vs code bottom "Watch  Sass" . 

**To Reproduce**
install extension
restart vs code

**Expected behavior**
Observer icon visible

**Screenshots**
![image](https://user-images.githubusercontent.com/78958958/213582512-88451c3e-c78a-4aba-a470-ce7e6255c3a9.png)

**Additional context**
version extension v1.8.23
Version vs code: 1.70.0 (user setup)

**Comment by TheRealSyler** [comment]
This extension is for `.sass` files only and there is no built in sass compiler, you might be looking for [this extension](https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass).
