### ISSUE TITLE
I'm trying to get a #region, #endregion tags to drive folding in the editor.

### ISSUE THREAD

**Issue by Hulley** [TheRealSyler/vscode-sass-indented#12]
**Describe the bug**
Folding doesn't work, even with other 3rd party plugins

**To Reproduce**
open a .sass file and try to create a custom fold

**Potential Fix**
in sass.language.json change
```
  "foldingStartMarker": "/\\*|^#|^\\*|^\\b|^\\.",
  "foldingStopMarker": "\\*/|^\\s*$",
```
to
 ```
  "foldingStartMarker": "/\\*|^#|^\\*|^\\b|*#?region|^\\.",
  "foldingStopMarker": "\\*/|*#?endregion|^\\s*$",
```

**Comment by TheRealSyler** [comment]
thanks for opening the issue, I have also noticed that you can't fold (anymore?), since I almost never fold my code I didn't really look into it, but I will try to fix it in the next version or the version after that.

**Comment by TheRealSyler** [comment]
Folding seems to be working again.
