### ISSUE TITLE
Auto-completion (hints) do not work in nested selectors (SASS)

### ISSUE THREAD

**Issue by enarvynn** [TheRealSyler/vscode-sass-indented#121]
Type: <b>Bug</b>

Auto-completion (hints) do not work in nested selectors

For example code: 

@media (max-width: 1199px)
    .container
        width: 960px
    .main-section
        min-height: 690px
    .left-wrapper
        img
            width: 750px
        &__rectangle-blue
            width: 500px
            height: 200px
        &__rectangle-orange
            width: 550px
            height: 200px
        &__rectangle-grey
            width: 500px
            height: 200px
    .right-wrapper
        right: 20px
    .main-section__first-elipse
        right: 10px
    .main-section__second-elipse
        top: 560px
    .second-section
        &__cards-box
            display: flex
            justify-content: center
    .cards-item
        width: 300px
        height: 300px
        margin-right: 20px
    .cards-item__img
        height: 270px
    .cards-item__text
        font-size: 30px
    .icons-item__img
        margin-right: 10px

// If I try to add something to the end of the code, Visual Studio does not offer me a hint (SASS)
// At the first level of nesting, hints work

Extension version: 1.8.26
VS Code version: Code 1.76.0 (Universal) (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:23:45.993Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv|--crash-reporter-id a542858a-ce5c-415d-8465-3b42d4cf2cf6|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30681850
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30672706
pythonb192:30669360
functionswalk:30687959
pythonms35:30686772

```

</details>

**Comment by TheRealSyler** [comment]
@enarvynn your code works for me, it says that you only have 0.08GB of free ram maybe vscode cannot allocate more memory that?, you could also look in the dev tools (help > Toggle Developer Tools) vscode might log something that could indicate what the problem is, let me know if you fixed your issue or have any idea how i could reproduce it.
