### ISSUE TITLE
Watch Sass not working

### ISSUE THREAD

**Issue by MohammedJabir18** [TheRealSyler/vscode-sass-indented#122]
Type: <b>Bug</b>

SASS not working 

Extension version: 1.8.26
VS Code version: Code 1.78.2 (b3e4e68a0bc097f0ae7907b217c1119af9e03435, 2023-05-10T14:39:26.248Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (1.92GB free)|
|Process Argv|--crash-reporter-id 0a7921b2-32b8-42f6-a670-d833ee2f894d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
a9j8j154:30646983
showlangstatbar:30737416
pythonms35:30701012
pythonfmttext:30731395
fixshowwlkth:30730052
hidesbindicator:30730055
pythongtdpathcf:30739705

```

</details>

**Comment by TheRealSyler** [comment]
@MohammedJabir18 sass watch is not a feature of the this extension.

**Comment by MohammedJabir18** [comment]
> @MohammedJabir18 sass watch is not a feature of the this extension.

Thank you for your response. I understand that Sass watch is not a feature of the Sass extension in VS Code. However, I'm still facing difficulties with compiling my Sass file to CSS. Could you please provide some guidance on how I can resolve this issue or suggest an alternative method for compiling Sass files in VS Code? I would greatly appreciate your assistance. Thank you.

**Comment by TheRealSyler** [comment]
@MohammedJabir18 you are probably looking for an extension like [this](https://marketplace.visualstudio.com/items?itemName=glenn2223.live-sass), or you can do manually by installing the [`sass`](https://www.npmjs.com/package/sass) package then you can run `npx sass index.sass index.css` or you can install it globally with `npm install -g sass`, then you don't need `npx`, you can also add the `-w` flag if you want it to automatically update when you save your sass files.
