### ISSUE TITLE
Everytime I save a Sass file its removing the ;(semi colon) from the end of the line and making my file break.

### ISSUE THREAD

**Issue by LeesDevVersion** [TheRealSyler/vscode-sass-indented#124]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.

**Additional context**

**Comment by TheRealSyler** [comment]
@LeesDevVersion thats how the `.sass` variant works, its `.scss` without brackets and semi-colons
