### ISSUE TITLE
VSCode color decorators vanish under certain conditions

### ISSUE THREAD

**Issue by HeyMyian** [TheRealSyler/vscode-sass-indented#126]
VSCode color decorators vanish when a property value is declared in a certain way that involves functions and SASS variables.

The bug comes from properties which allow comma-separated values, and mixing CSS colors and SASS variables in the `rgba()` function, like so:
```sass
.class
  box-shadow: 0 2px 2px rgba($black, 0.5), 0 4px 4px rgba(#fff, 0.5)
```

As far as I understand, this is a valid declaration and the CSS comes out as expected. There are no errors when compiling this SASS file. But writing it like this removes all VSCode color decorators in the editor, even when the line is commented out. Compare the two following screenshots:

✅ VSCode color decorators work as expected:
![2024-07-02___18_47_45](https://github.com/TheRealSyler/vscode-sass-indented/assets/60368695/0916454b-f847-4e35-86e3-ac68861cd46d)

❌ A new class was added, which mixes on the same line CSS color and SASS variable in the function parameters. All VSCode color decorators vanish:
![2024-07-02___18_48_04](https://github.com/TheRealSyler/vscode-sass-indented/assets/60368695/7055e717-88aa-40c3-a463-6463891da357)

Code for copy paste convenience:
```sass
$black: #000
$white: #fff

.class0
  box-shadow: 0 2px 2px #000, 0 4px 4px $white
.class1
  box-shadow: 0 2px 2px rgba(#000, 0.5), 0 4px 4px rgba(#fff, 0.5)
.class2
  box-shadow: 0 2px 2px rgba($black, 0.5), 0 4px 4px rgba($white, 0.5)
.class3
  box-shadow: 0 2px 2px rgba($black, 0.5), 0 4px 4px rgba(#fff, 0.5)
```

I apologize if I created the issue in the wrong repository. It is not entirely clear to me where to go with this.

**Comment by TheRealSyler** [comment]
@HeyMyian should be fixed now, the next extension version should be available in the next couple of hours

**Comment by HeyMyian** [comment]
Thank you, that was so fast 😃 The time I spent trying to figure out why my decorators went missing is longer than the time between posting my issue and your fix.
