### ISSUE TITLE
Error when going from file to settings page

### ISSUE THREAD

**Issue by ssang** [TheRealSyler/vscode-sass-indented#13]
**Describe the bug**
There is an error that pops up in the console whenever I go from any file to the settings page. If I have this extension installed along with Eno Snippets, it will also crash the extensions host. If I don't have Eno Snippets enabled, it will just display the error in the developer console.

**To Reproduce**
Open up a sass file (or any file)
Go to the settings UI

**Screenshots**
![Error in Developer Console](https://user-images.githubusercontent.com/4543338/63968490-b688e800-ca54-11e9-9ca4-ca6ddf850afe.png)

The TypeError is what appears if Eno Snippets is not installed.

**Desktop (please complete the following information):**
 - OS: Happens on both my iMac and PC
 - Version: 1.61

**Comment by TheRealSyler** [comment]
@ssang i can't replicate the issue so im closing it for now, try the newest version(1.6.2) maybe i fixed it without knowing it.

what i did to try to replicate the bug is i installed eno snippets and opened a sass file and then the setting im not geting any errors related to sass or eno snippets.

**Comment by ssang** [comment]
Yes it seems to be fixed in 1.62! Thanks
