### ISSUE TITLE
Keeps hanging 

### ISSUE THREAD

**Issue by kirko9x** [TheRealSyler/vscode-sass-indented#14]
Issue Type: <b>Bug</b>

When I click on "watch Sass" it just keeps hanging and nothing is happening. 
The code is not transfered from sass to css. Morveover, the buttong "watch sass" can be clicked one time onyl and then it is just frozen ( not clickable) 

Extension version: 1.6.2
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD A12-9700P RADEON R7, 10 COMPUTE CORES 4C+6G (4 x 2495)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.46GB (2.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by TheRealSyler** [comment]
i think you mixed up this extension with another extension, there is no compile functionality in the indented sass extension.
