### ISSUE TITLE
Some update completely broke formatting

### ISSUE THREAD

**Issue by codysherman** [TheRealSyler/vscode-sass-indented#15]
**Describe the bug**
A lot of things broke in the latest version, it's really messing up the formatting of our files. Hard to pinpoint a specific root cause, other than to just say that it's really screwing up our file.

**To Reproduce**
* Items with commas now remove the line breaks above them (h1, h2, h3)
* `svg` can't be styled anymore, it treats that as a CSS rule instead of an element.
* Some things are just now randomly double indented within. For example everything underneath `input.chaser-checkbox[type='checkbox']` is getting 4 spaces indented instead of 2.

**Expected behavior**
It should format as before.

**Screenshots**
![Screenshot 2019-09-02 at 6 12 11 PM](https://user-images.githubusercontent.com/371608/64135363-48725700-cdad-11e9-84b7-e074ed2ab2c9.png)
![Screenshot 2019-09-02 at 6 11 25 PM](https://user-images.githubusercontent.com/371608/64135364-48725700-cdad-11e9-8f7a-8d7e9f869f55.png)
![Screenshot 2019-09-02 at 6 10 21 PM](https://user-images.githubusercontent.com/371608/64135365-48725700-cdad-11e9-9e2b-da0634a3f189.png)

**Desktop (please complete the following information):**
 - OS: [Chrome OS 75]
 - Version [1.6.2]

**Additional context**

**Comment by TheRealSyler** [comment]
@codysherman thanks for opening the issue, i will look into it, i might be able to publish a new version later today that addresses your issues, if not today then tomorrow.

**Comment by TheRealSyler** [comment]
@codysherman should be fixed, if not reopen the issue.

**Comment by codysherman** [comment]
Hey man thanks for the fast answer and change, but unfortunately it appears to still be broken. Now it's putting rules not tabbed in at all:

```
body
  color: red
```

becomes

```
body
color: red
```

**Comment by TheRealSyler** [comment]
@codysherman yeah i also just found out about it, i updated my fancy check for html tags regex and it works, the only issue is that when you have a tag without any other stuff attached to it, the regex fails, the fix for know is use `///R` it sets the indenation level.

```sass
body
  ///R
  color: red
  // everything until the next selector will be indented based on the indentation of ///R  
```
it will be fixed in the next version but im not going to update until i change more stuff.
