### ISSUE TITLE
Mixing tabs + spaces does not get fixed nor raise warning

### ISSUE THREAD

**Issue by torleif** [TheRealSyler/vscode-sass-indented#17]
**Is your feature request related to a problem? Please describe.**
When you have file that contains both tabs and spaces, they both get used

**Describe the solution you'd like**
Keep the usage of tabs or spaces consistent 

**Describe alternatives you've considered**
Other extensions have an option to set the number of spaces, or to use tabs

**Additional context**
it's great this extensions works out the box

**Comment by TheRealSyler** [comment]
@torleif should't be to difficult to implement, i will try to add it to the next version.
