### ISSUE TITLE
Unable to nest anchor tags inside list-item tags

### ISSUE THREAD

**Issue by mainangethe** [TheRealSyler/vscode-sass-indented#19]
**Describe the bug**
When creating nav bar styles within an unordered list tag. The system auto corrects the nesting without properly considering the anchor tag.

**To Reproduce**
Create an unordered list tag and add some styles
Nest a list-item tag and add some styles
Also nest an anchor tag inside the list-item tag
Save the .sass file

**Expected behavior**
I expect the system to honor my nesting and recognize the anchor tag as a nesting inside the list-item tag. However it is autocorrecting and pushing the anchor tag as a nesting inside the unordered list rendering it's styles as part of the list item tag and not the anchor.

**Screenshots**
![sass-lint-issue](https://user-images.githubusercontent.com/41260290/64673065-dae1bd00-d475-11e9-8aba-fe2b392a0c49.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04

**Comment by TheRealSyler** [comment]
@mainangethe should be fixed in 1.6.4, if it isn't please reopen this issue.
