### ISSUE TITLE
Unable to nest styles for my function

### ISSUE THREAD

**Issue by webspilka** [TheRealSyler/vscode-sass-indented#20]
**Describe the bug**
When creating styles for my function, formatter delete nesting styles

**To Reproduce**
```sass
// my function is 
=desktop
  @media screen and (min-width: $desktop)
    @content

// test.sass:
.footer
    margin-top: 3rem
    +desktop
        padding-top: 220px

// formated test.sass
.footer
    margin-top: 3rem
    +desktop
    padding-top: 220px
```

**Expected behavior**
Formatter must add idents for style scopes after line starts with "+" symbol

**Screenshots**
![image](https://user-images.githubusercontent.com/1138069/65582963-0640cd80-df87-11e9-9491-c7b56b3ba34a.png)

**Desktop (please complete the following information):**
 - OS: [mac.os 10.14.6]
 - Version (of the extension) [1.6.4]

**Additional context**

**Comment by TheRealSyler** [comment]
should be fixe now.
