### ISSUE TITLE
After update to 1.6.5: I get message "There is no formatter for 'sass'-files installed" 

### ISSUE THREAD

**Issue by webspilka** [TheRealSyler/vscode-sass-indented#21]
**Describe the bug**
after yesterday's update to 1.6.5, formatting no longer works

**To Reproduce**
- update to 1.6.5

**Screenshots**
![image](https://user-images.githubusercontent.com/1138069/65667939-72840580-e049-11e9-9ced-783b359665d1.png)

**Desktop (please complete the following information):**
 - OS: [mac.os 10.14.6]
 - Version (of the extension) [e.g. 1.6.5]

**Comment by TheRealSyler** [comment]
i hate it when, it works locally and then it brakes after publishing, it seems that the entire extension is broken,i will fix it later today.

**Comment by TheRealSyler** [comment]
should work again, if it doesn't, please reopen this issue.
