### ISSUE TITLE
css property name autocomplete suggestion not working

### ISSUE THREAD

**Issue by noe132** [TheRealSyler/vscode-sass-indented#22]
**Describe the bug**
Type any css property names to trigger css autocomplete, broken in `1.6.5`

**To Reproduce**
1. open any sass file
2. type `flfl`
3. no suggestion available
![image](https://user-images.githubusercontent.com/2271900/65672262-4e411c80-e07b-11e9-9f00-150885ab55c7.png)

**Expected behavior**
there should be an autocomplete popup like this
![image](https://user-images.githubusercontent.com/2271900/65672232-41bcc400-e07b-11e9-9808-0d5126d2043e.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version (of the extension) 1.6.4

**Additional context**
`1.6.4` seems ok.

**Comment by TheRealSyler** [comment]
yeah i broke the extension yesterday, worked locally, will fix it later today.

**Comment by vlad-tircomnicu** [comment]
Almost reinstalled my laptop :))

**Comment by TheRealSyler** [comment]
so i reinstalled my node modules, and added the tslib ot my package.json, i think this is all i have to do to make it work again, i tested it and it works now, let me know if doesn't work.

**Comment by vlad-tircomnicu** [comment]
Working for me right now! Thank you!
