### ISSUE TITLE
Broken color decorators

### ISSUE THREAD

**Issue by svilenmarkov** [TheRealSyler/vscode-sass-indented#24]
**Describe the bug:**
Hex codes always display as white and color keywords don't even get recognized as colors. 

**Screenshots**
![example](https://user-images.githubusercontent.com/7613769/67478817-bbcd7200-f654-11e9-82b8-9ff918d90b5c.png)

**Desktop:**
 - OS: Win10
 - Version (of the extension): 1.6.7

**Comment by TheRealSyler** [comment]
ill look into it, red should not be recognized, because its just not implemented, hex colors should work but i have also seen weird behavior, i will fix it later today probably wont update the extension until i have fixed/added more stuff.

**Comment by TheRealSyler** [comment]
its fixed, im closing this later when i publish the next version.
