### ISSUE TITLE
minify sass file when paste

### ISSUE THREAD

**Issue by mateusavila** [TheRealSyler/vscode-sass-indented#25]
When pasting a code, the autoformater removes all spaces and minify the file. 

Happen in:
 - Windows 10
 - Version 1.39.2

**Comment by TheRealSyler** [comment]
@mateusavila not sure what you mean, please give an example (screenshot).

**Comment by mateusavila** [comment]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/2197079/67863238-48b77600-fb02-11e9-8b4c-36d535f7ec6a.gif)

I'm just pasting anything, then the autoformat removes all the tabs.

**Comment by mateusavila** [comment]
Hi!

Only happens in sass files. Even in .Vue files with sass inside works pretty well.

I'll test later.

**Comment by mateusavila** [comment]
The console returns empty. Fails silently.

**Comment by TheRealSyler** [comment]
i can't help you if cannot reproduce the bug and i have no clue where it comes from, im sorry but i can't help you with this issue.
