### ISSUE TITLE
@use support

### ISSUE THREAD

**Issue by theovgl** [TheRealSyler/vscode-sass-indented#26]
The SASS team seems to have created a new feature called `@use`. It seems to be very useful and will even replace `@import` in the long term.
Unfortunately I don't have the impression that sass-indented is compatible.

Source : [Css-Tricks](https://css-tricks.com/introducing-sass-modules/)

**Comment by TheRealSyler** [comment]
thanks for making me aware, i will try to add it to the next version.

**Comment by TheRealSyler** [comment]
Note: add [meta](https://sass-lang.com/documentation/modules/meta) module before closing.

**Comment by Limonische** [comment]
If you use @use like so:
```
@use 'something' as somethingElse
```

"as" and "somethingElse" lack syntax highlighting.

**Comment by Limonische** [comment]
Also since its related, there is no support for the new @forward feature; And everything typed after @use, @import or @forward also has no syntax highlighting.

**Comment by TheRealSyler** [comment]
it works on my end not sure what might cause the lack of syntax highlighting, ill look into the @forward thing.
![image](https://user-images.githubusercontent.com/46901787/68740231-e9219600-05ea-11ea-93e1-6ec42fa3b412.png)
