### ISSUE TITLE
@functions isn't recognized by TM Scopes. Name of @import is no longer a string

### ISSUE THREAD

**Issue by Limonische** [TheRealSyler/vscode-sass-indented#27]
**Describe the bug**
If you try to inspect @function statement with "Inspect TM Scopes" it freezes in infinite loading. Color highlighting for @function is broken. Same goes for mixins.
Name of file in @import is no longer a string.

**To Reproduce**
Use "Inspect TM Scopes" in vscode-insiders 1.41.0

**Expected behavior**
Color highlighting for @function should work, it also should be accessible by "Inspect TM Scopes". Same for mixins.
Name of file in @import statement should be a string.

**Screenshots**
![image](https://user-images.githubusercontent.com/47951826/68618737-1121d400-04db-11ea-9375-68438d6f36f5.png)
```
@function strip-unit($value)
	@return $value / ($value * 0 + 1)

@function get($map, $keys...)
	@each $key in $keys
		$map: map-get($map, $key)
	@return $map
```
![image](https://user-images.githubusercontent.com/47951826/68619553-bf7a4900-04dc-11ea-9338-37db1bdfe7a8.png)
```
=media($width...)
	@if length($width) == 1
		@media screen and (min-width: nth($width, 1))
			@content
	@if length($width) == 2
		@media screen and (min-width: nth($width, 1)) and (max-width: nth($width, 2))
			@content
```

![image](https://user-images.githubusercontent.com/47951826/68618827-44646300-04db-11ea-9488-96eb0fabda9f.png)

```
@import 'imports/imports'
```

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Version (of the extension) 1.6.8

**Comment by TheRealSyler** [comment]
@Limonische the highlighting is already fixed in the latest version (on my local machine), not sure what  "Inspect TM Scopes" is but ill look into it.

**Comment by Limonische** [comment]
Its a feature in vscode that allows you to look at language token types and detect which colors and styles are applied to it. You can access it by ctrl/command + shift + p and then selecting "Developer: Inspect TM Scopes"
![image](https://user-images.githubusercontent.com/47951826/68619860-521ae800-04dd-11ea-9dee-16e57c34ab8d.png)

Thank you for your fast reply.

**Comment by TheRealSyler** [comment]
yeah just downloaded vscode insiders its a really cool feature, it should already be fixed, the reason why the highlighting doesn't work is this regex `[[\\w-]+` as you can see the regex is invalid i catched that shortly after publishing

**Comment by Limonische** [comment]
Thank you again! Can i ask you when this new release with fixes will be shipped?

**Comment by TheRealSyler** [comment]
im not sure i will try to have it published tomorrow or the day after that.

**Comment by Limonische** [comment]
Nice. Keep your the good work :)

**Comment by TheRealSyler** [comment]
@Limonische hey if you want it fixed right now, go to this repo and download `sass-indented-1.6.8.vsix` then search for the `install.vsix` extension, right click on the file and chose `install extension`, you might need to download the entire repo because i don't think that github lets you download single files.

**Comment by TheRealSyler** [comment]
also not sure if it auto updates extensions after you install them from a files so you might need to uninstall and reinstall the extension when the new version comes out.
