### ISSUE TITLE
Syntax highlight is broken

### ISSUE THREAD

**Issue by limbosounds** [TheRealSyler/vscode-sass-indented#28]
**Describe the bug**
Wrong highlight color of class selector with tag name

**To Reproduce**
1. Write class selector with tag name.

**Expected behavior**
Class selector will be highlighted red instead of yellow.

**Screenshots**
![Screenshot from 2019-11-14 11-27-25](https://user-images.githubusercontent.com/26549754/68844126-f9607080-06d1-11ea-98d9-5a2dfa4cf91b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Version (of the extension): 1.6.9

**Additional context**
Using "Monokai Dimmed" theme

**Comment by TheRealSyler** [comment]
@limbosounds i already know why that is, i will fix it soon ish.

**Comment by limbosounds** [comment]
@TheRealSyler thank you :)

**Comment by TheRealSyler** [comment]
fixed, but i have to add other stuff before i publish the next version.
