### ISSUE TITLE
Support new syntax: `map.get()`

### ISSUE THREAD

**Issue by dtvn** [TheRealSyler/vscode-sass-indented#34]
In the pass, we have `map-get()`. With the new sass, we can do this:

```
@use 'sass:map';
body {
    color: map.get($color, 'text');
}
```

But our current ext sees it as an error. It would be cool this can be fixed soon.

Reference:
- https://sass-lang.com/documentation/modules/map

**Comment by TheRealSyler** [comment]
your snippet is scss, is this extension is for sass are you sure you opened the issue in the right place?
if this is the right repo, what do you mean by error? please elaborate.

**Comment by dtvn** [comment]
My apologize, I always used it with scss and it worked fine until the new upgrade of SASS so I thought the ext also support scss. I've changed the file to sass format and it works perfectly fine.

**Comment by TheRealSyler** [comment]
@dtvn no worries, scss is supported without extensions, you only need the extension when you want to use sass.
