### ISSUE TITLE
Passing Arguments to Content Blocks Support

### ISSUE THREAD

**Issue by juliomotol** [TheRealSyler/vscode-sass-indented#37]
**Describe the bug**
The linter is saying there is a problem with using `@content ($param)` and `@mixin () using ($param)` but I'm able to build the SCSS. See [SASS Documentation](https://sass-lang.com/documentation/at-rules/mixin#passing-arguments-to-content-blocks)

**To Reproduce**

    @mixin media($types...) {
      @each $type in $types {
        @media #{$type} {
          @content($type);
        }
      }
    }

    @include media(screen, print) using ($type) {
      h1 {
        font-size: 40px;
        @if $type == print {
          font-family: Calluna;
        }
      }
    }

**Expected behavior**
There shouldn't be any problems found with using `@content ($param)` and `@mixin () using ($param)`

**Screenshots**
![image](https://user-images.githubusercontent.com/21353103/74853852-72c6c980-5379-11ea-8a55-11b629efc117.png)
![image](https://user-images.githubusercontent.com/21353103/74853908-883bf380-5379-11ea-9744-9c6f7f0dc3b4.png)

**Additional context**
This is a Vue CLI project with sass related dependencies as follow:
- sass: ^1.25.0
- sass-loader: ^8.0.2

**Comment by TheRealSyler** [comment]
this extension is for `.sass` files only, for issues with the built in support try opening your issue in the vscode repo.
