### ISSUE TITLE
Auto complete failure

### ISSUE THREAD

**Issue by 15774211127** [TheRealSyler/vscode-sass-indented#38]
**Describe the bug**
No attribute prompt after ‘display’ entered

**To Reproduce**
1. Enter display

2. Select dispaly at the prompt

3. Press enter

4. Automatic complete ‘display’

**Expected behavior**
prompt [block、contents、flex、inline、inline-block]

**Screenshots**

![1](https://user-images.githubusercontent.com/17411462/77141212-0c87b080-6ab7-11ea-899a-e3fc578479de.gif)

![2](https://user-images.githubusercontent.com/17411462/77141227-17424580-6ab7-11ea-9687-932a04d913c7.gif)

![3](https://user-images.githubusercontent.com/17411462/77141254-2fb26000-6ab7-11ea-9b2e-c3acb40bde0b.gif)

**Additional context**

**Comment by TheRealSyler** [comment]
@15774211127 go to the settings and disable `sass.autocomplete.useExperimentalData`, i have also noticed that there are some problems with the experimental data, i will probably turn it off by default in the next version or if will see what i can do to improve the data.

**Comment by dvdkon** [comment]
This is still a problem for me and manually adding `"sass.autocomplete.useExperimentalData": false` doesn't help (it seems this option is not present in the current version).

**Comment by TheRealSyler** [comment]
@dvdkon yes that option was removed some time ago i think, i guess i need to update the readme, not sure why you are having that problem, feel free to open a new issue, add screenshots and the sass text so that i can reproduce the error.

**Comment by dvdkon** [comment]
All right, thanks for the quick reply!
