### ISSUE TITLE
(Improvement) Support autocomplete in Vue template files

### ISSUE THREAD

**Issue by Crucial288** [TheRealSyler/vscode-sass-indented#4]
Vue template files currently don't care about autocomplete for Sass.
Syntax highlighting works properly inside Vue sass style tags, but autocomplete does not.

**Comment by TheRealSyler** [comment]
i will look into it, once  im finished with version 1.6, meaning in a 1 or 2 weeks.

**Comment by TheRealSyler** [comment]
@Crucial288 i have added autocomplete in the latest version, since i will update the extension today, you should be able to use autocompletion inside vue, later today, im not that familiar with vue but i think it should work, if it doesn't let me know.

**Comment by TheRealSyler** [comment]
[bb952ab](https://github.com/TheRealSyler/vscode-sass-indented/commit/bb952abf436df0f1a99fd06c23d37b6a31390780)

**Comment by Crucial288** [comment]
Just wanted to confirm I checked this morning and the autocomplete now works as expected!
