### ISSUE TITLE
Configurable indent to two or four spaces

### ISSUE THREAD

**Issue by junmiron** [TheRealSyler/vscode-sass-indented#44]
**Is your feature request related to a problem? Please describe.**
I always get an error with Sass Lint because the indent is four spaces and not two.

**Describe the solution you'd like**
To be able to configure indent to be two or four spaces, for the automatic indent and formatter.

**Describe alternatives you've considered**
I considered disabling the automatic indent and configuring the Linter to four spaces, but I really like the indent to be two spaces and I really like to have the automatic indent when I press enter.

**Additional context**
NA.

**Comment by TheRealSyler** [comment]
you can already configure how many spaces you want, just use the [vscode settings](https://code.visualstudio.com/docs/editor/codebasics#_indentation) and the formatter will use the vscode settings.
