### ISSUE TITLE
Sass Compiler and it's problems with display: grid;

### ISSUE THREAD

**Issue by elmokirk** [TheRealSyler/vscode-sass-indented#46]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

**Describe the bug**
The Compiler doesn't include the normal "grid-column / grid-row" but it includes the browserfixed which is wired.
Additional to that does the repeat() function some mistakes, in which it outputs following: 
"-ms-grid-columns: (1fr)[6];"

**To Reproduce**
create a grid and use the repeat function .. After the compiling there should be the named mistakes

**Expected behavior**
I expect to work with this compiler which is compiling all the grid-speciefied code correctly in css with browserfixed

**Screenshots**
If you add screenshots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.
![image](https://user-images.githubusercontent.com/60427014/80381465-43649980-88a1-11ea-9bef-e4150cae6854.png)

**Additional context**
Thanks a lot :)

**Comment by TheRealSyler** [comment]
the extension is only for the `.sass` syntax.
