### ISSUE TITLE
struggling with JSDoc style comment blocks indentation

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/vscode-sass-indented#47]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

I'm not sure!

**Describe the bug**
I use JSDoc syntax to document a lot of parts throughout all my apps.

I often need to make some minimal documentation for SASS variables as well.

However, while any JS/TS/Vue file works really well with JSDoc style comment blocks in VSCode, Sass files seem to try and work against me when trying to type a JSDoc comment...

I know it's possible by just adding some sort of snippet that expands into a JSDoc comment block, but the problem is when pressing ENTER, in JS/TS/Vue files it automatically adds the proper indentation and * in front of the new line inside the comments.

In Sass files, not only is the indentation is consistently wrong when pressing ENTER in a comment block and it's not helping me at all by adding * or the closing */ tag...

**To Reproduce**

See GIF: 
![2020-05-01 14 51 29](https://user-images.githubusercontent.com/3253920/80785749-4d95d900-8bbc-11ea-988b-463bdeac6db1.gif)

**Expected behavior**

I expect it to automatically
- add the correct indentation
- add the `*` in front of each row on ENTER inside the comment block
- add the close `*/` tag

**Comment by TheRealSyler** [comment]
@mesqueeb i will put it on my todo list.

**Comment by mesqueeb** [comment]
@TheRealSyler Wow thank you so much!! 😍 

Here is an example of a `color.sass` file I'm maintaining for a project:

```sass
/**
 * There is no pure black in this interface, instead there is the awesomeness that is Blue-Zodiac.
 * Use blue-zodiac instead of black, and use it’s opacity variants for text and icon colors.
 * /
$c-blue-zodiac: #0E2348
$c-primary: rgba($c-blue-zodiac, 0.96)
$c-secondary: rgba($c-blue-zodiac, 0.72)
$c-hint: rgba($c-blue-zodiac, 0.56)
$c-disabled: rgba($c-blue-zodiac, 0.28)
```

PS: I'm working on a SASS file parser that can extract these variables & JSDoc style comments, and automatically create a style guide exposé. So both designer and programmer have the same source of truth.

**Comment by TheRealSyler** [comment]
@mesqueeb i might have a parser that already can do what you want with no or little changes, im currently working on version 2 of the extension and part of that is creating a parser that parses a file into nodes, just download the lsp-branch of this extension and look into the `server/src/abstactSyntaxTree` folder, you can run tests by running `yarn test:watch` in the server folder, just keep in mind that its finished.

**Comment by mesqueeb** [comment]
😅
I’m not so advanced with these things as you i think.......

**Comment by mesqueeb** [comment]
@TheRealSyler I starter working on my sass parser, and I tried your branch!

however,
```
"dependencies": {
    "sass-lsp-server": "/home/syler/Documents/GitHub/sass-lsp-server",
    "vscode-languageclient": "^6.1.3"
  }
```
your dependency is not hosted on github? :D 

<img width="792" alt="image" src="https://user-images.githubusercontent.com/3253920/90227381-6a92a700-de4f-11ea-92e4-8efe292e95c3.png">

**Comment by TheRealSyler** [comment]
you have to download [this repo](https://github.com/TheRealSyler/sass-lsp-server) and link it manually, im currently not actively working on that project, but if you run into any issues feel free to let me know.

**Comment by TheRealSyler** [comment]
and i think you only need the `sass-lsp-server`, at the time i had the server and the extension in the same repo but now its in two separate repos.

**Comment by TheRealSyler** [comment]
@mesqueeb i think i can close this reopen if you feel that it should stay open.

**Comment by mesqueeb** [comment]
@TheRealSyler thanks again for all your help so far!
