### ISSUE TITLE
Bug: adds indentation when it should not

### ISSUE THREAD

**Issue by mesqueeb** [TheRealSyler/vscode-sass-indented#48]
**_IMPORTANT_**: if the bug is related to the formatter please open the issue in the formatter [repo](https://github.com/TheRealSyler/sass-formatter/issues/new?assignees=TheRealSyler&labels=bug&template=bug_report.md&title=)

I'm not sure!

**Describe the bug**

Often when I'm defining sass variables, I'd like them to stay on the root level  → 0 indentation.

I'm not sure why, and if it's this sass plugin, but every time it tries to automatically add indentation in front of my variables when I press ENTER in front of the variable.

**To Reproduce**

![2020-05-01 15 36 00](https://user-images.githubusercontent.com/3253920/80787554-ce0b0880-8bc1-11ea-8e05-62142cec6878.gif)

**Expected behavior**
Not add indentation when defining a variable.

**Comment by TheRealSyler** [comment]
this is expected behavior, i didn't implement it so im not sure how it works exactly but you can use `alt + arrow(up/down)` to move a line.
