### ISSUE TITLE
Sass style block comment won't close until */

### ISSUE THREAD

**Issue by 747** [TheRealSyler/vscode-sass-indented#52]
**Describe the bug**
[Sass block comment is indentation-based](https://sass-lang.com/documentation/syntax/comments#in-sass), where the closing mark `*/` isn't needed when the line starts with `/*`.
But in the latest version of highlighter, the comment extends forever until it sees a closing token. On the other hand, indented block comments seems not recognized.

**To Reproduce**
Minimal example:
``` sass
/* this is a comment
#valid-selector

/* reset */
#another-selector
  /* this is also a comment
```

**Expected behavior**
The `#valid-selector` and `#another-selector` lines should be highlighted as selectors, and the rest as comments.

**Screenshots**
![image](https://user-images.githubusercontent.com/3427854/87862040-c3713b80-c986-11ea-8fc3-4deab458133c.png)

**Additional context**
My Sass file was highlighted correctly back in April, so it seems a recently introduced bug.
I suspect that this commit https://github.com/TheRealSyler/vscode-sass-indented/commit/5dd43f5b575df20a2a9c4a760b8b752c4898fc73 is to blame.

**Comment by TheRealSyler** [comment]
should be fixed, if it there still is an issue please leave a new comment or open a new  issue.

**Comment by 747** [comment]
Thanks for quick fixing. It works well with my current file, but still needs work for such a case like:
``` sass
#selector
  /* &::before
    content: "is comment"
  content: "is not comment"
```

It shouldn't consume same-level declarations following it.
