### ISSUE TITLE
(Improvement) Support autocomplete in Svelte files

### ISSUE THREAD

**Issue by dummdidumm** [TheRealSyler/vscode-sass-indented#57]
**Is your feature request related to a problem? Please describe.**
I do not get autocompletions inside Svelte files.

**Describe the solution you'd like**
Support autocompletion in Svelte files where `<style lang="sass">` is present.

```html
<script>
   ....
</script>
   ...
<style lang="sass">
   get autocompletions in here
</style>
```

**Additional context**
Basically the same support Vue got through #4

**Comment by TheRealSyler** [comment]
i can look into it, i also want to point out that this extension is for `.sass` only, `.scss` is handled by a build in vscode extension.

**Comment by dummdidumm** [comment]
Oops, sorry, meant to type `sass`, not `scss` 😄 Thank you for looking into it!

**Comment by TheRealSyler** [comment]
should work in the latest version, if there are any issues feel free to open a new issue.

**Comment by dummdidumm** [comment]
Works perfectly, thanks for the quick implementation! 🎉
