### ISSUE TITLE
Block comments

### ISSUE THREAD

**Issue by hurick** [TheRealSyler/vscode-sass-indented#6]
**Describe the bug**
Using `Visual Studio Code`, when upgrading to the `1.6.0` version, the `.sass` files that had block comments are now commented everywhere.

**To Reproduce**
You just need to open a `.module.sass` (I am using the `create-react-app` package) file that have block comments, actually.

**Expected behavior**
Files should be like version `1.5.2` when using block comments, right?

**Screenshots**
Version 1.5.2
<img width="901" alt="Screen Shot 2019-08-06 at 9 51 02 AM" src="https://user-images.githubusercontent.com/14249327/62541372-0d254c80-b830-11e9-80fa-ad08bfeddfbd.png">

Version 1.6.0
<img width="893" alt="Screen Shot 2019-08-06 at 9 51 24 AM" src="https://user-images.githubusercontent.com/14249327/62541358-08f92f00-b830-11e9-862b-dda85f643880.png">

**Desktop (please complete the following information):**
 - MacOS Mojave
 - Version 10.14.6 (18G87)

**Comment by TheRealSyler** [comment]
@hurick  i must admit i am really confused by block comments in sass i tried to make some changes, and it seems like i did not revert them, thought i did, i will take a look at it right now, i should be able to fix this in under 1 one hour, when its fixed i will update the extension, if you could paste the code as text that would be great.

**Comment by hurick** [comment]
@TheRealSyler no problems, mate.
Thank you so much for giving some attention to this problem! 🙏

**Comment by TheRealSyler** [comment]
[bb952ab](https://github.com/TheRealSyler/vscode-sass-indented/commit/bb952abf436df0f1a99fd06c23d37b6a31390780)

**Comment by hurick** [comment]
@TheRealSyler I already tested and it's working like a charm again.
Thank you a lot for this fix 🙏
