### ISSUE TITLE
highlighting problem

### ISSUE THREAD

**Issue by babakfp** [TheRealSyler/vscode-sass-indented#65]
Hello.
In a .sasss fine, write:
```scss
$v: ()
```
There is going to be a highlighting problem on the parentheses.

**Comment by TheRealSyler** [comment]
i cant't reproduce the problem, please add more info.

**Comment by babakfp** [comment]
Hi
Sorry, I was forgotten to respond.
![Capture](https://user-images.githubusercontent.com/44144724/107237476-a0b67b00-69db-11eb-9847-119f530e1de7.PNG)
This is what I see in a .sass file. The color of the left and right parentheses isn't the same.

**Comment by TheRealSyler** [comment]
i had  a bracket colorizer extension enabled now i can reproduce the issue.
