### ISSUE TITLE
How is it supposed to work?

### ISSUE THREAD

**Issue by sKopheK** [TheRealSyler/vscode-sass-indented#69]
Hi,
just instaled the extension into VS Code, but it does not format anything upon saving. Syntax highlighting seems to be supported by VS Code out of the box without any extensions (confirmed upon starting in dev mode with all extensions disabled). 
Q: not able to navigate to mixin definition inside another file. is it supported?

**Comment by TheRealSyler** [comment]
are you using .sass or .scss?, this extension is for .sass only, definition navigation is not (yet? #40) implemented.

**Comment by TheRealSyler** [comment]
also formatting on save has to be enabled somewhere in the editor options.

**Comment by sKopheK** [comment]
i'm using SCSS, which is technically also SASS, just another syntax, right?
worth mentioning in the documentation then ;)
