### ISSUE TITLE
Please check validity of the block starting from line #1 (CssSyntaxError)stylelint(CssSyntaxError)

### ISSUE THREAD

**Issue by TacitBrawler** [TheRealSyler/vscode-sass-indented#74]
The bug persists right at the first line.
version: 1.8.15

![Screenshot (25)](https://user-images.githubusercontent.com/74355872/106754922-8d11ba00-6653-11eb-9082-41bce10ca904.png)

**Comment by TacitBrawler** [comment]
Alright! when the file saved under '.scss' extension, it is working!
Only going haywire when it is a '.sass'.
sass has it's mapping missing  on ".map" file.
could someone please explain why this is happening?

**Comment by TheRealSyler** [comment]
@TacitBrawler  you cannot use brackets in the `.sass` syntax, regardless the error is definitely not from this sass extension.

this extension is only for the `.sass` syntax, here is an example
```sass
div
  margin: 20px
````
this is the `.scss` syntax which is not supported by this extension.
```scss
div {
  margin: 20px
}
````
