### ISSUE TITLE
Two line comments in a .sass file

### ISSUE THREAD

**Issue by babakfp** [TheRealSyler/vscode-sass-indented#75]
Hi
As you see, those two lines are considered as a comment. In the vscode, the second line isn't highlighted as a comment. It is shown as a normal text.
```sass
// This comment won't be included in the CSS.
  This is also commented out.
$something: something
```
From the [SASS comments documentation](https://sass-lang.com/documentation/syntax/comments), you can see how a comment can be written in a `.sass` file.

**To Reproduce**
1. Create a `.sass` file. For example `index.sass`
2. Write the code below:
```sass
// This comment won't be included in the CSS.
  This is also commented out.
```
Don't forget the tab for the second line.

**Expected behavior**
Both lines considered as a comment and highlighted as a comment. like how you see the Github is highlighted it.
```sass
// This comment won't be included in the CSS.
  This is also commented out.
$something: something
```

**Screenshots**
![Capture](https://user-images.githubusercontent.com/44144724/107245791-67ced400-69e4-11eb-84a9-c349a38e58bb.PNG)
```sass
// This comment won't be included in the CSS.
  This is also commented out.
```

**Comment by TheRealSyler** [comment]
sorry that i didn't respond earlier, i will look into it, it might take a long time though.

**Comment by babakfp** [comment]
No worries. Thanks a lot.

**Comment by RobertSandiford** [comment]
I don't think is a very important issue - it's pretty weird syntax to begin with.

But I had a look at it to see if I could solve it 

```
"begin": "\\",
"pattern": [
    {
        "begin": "(?<=//)",
        "end": "^(?!  |    |        |\t))",
        "patterns: [
            { "include": "#comment-tag" }
        ]
    }
],
"end": "(?<=(^(?!  |    |        |\t)))",
```

Begin with //
Then create a sub-pattern
Subpattern look-behinds to find the //, and start matching. Maybe this could just be .* ?
Subpattern continues until it finds a line not starting with indentation (2, 4, 8 spaces or tab)
Main pattern does a lookbehind for the same thing. Perhaps this can just be .* ?

Maybe issue here is getting the right indentation levels. Was thinking about capturing the indentation before the // and store it, then check the later indentation again it. But maybe it needs a config where the indentation used is specified instead.

Seems like limitations could make it difficult.

Just posting in case anyone is interested in thinking about the problem
