### ISSUE TITLE
Add an option to disable the distinct highlighting of units

### ISSUE THREAD

**Issue by AradAral** [TheRealSyler/vscode-sass-indented#76]
Hi. I prefer Sass's indented syntax over SCSS, and I tried many times to use this plugin, but one thing that annoys me very much is the fact that units are colored differently than the number preceding them.

I propose this would either be disabled entirely (maybe it's just me but I think it's just unnecessary clutter) or at least an option would be available that lets us disable it. This would make the syntax highlighting more similar to VS Code's native SCSS and CSS code syntax highlighting (and also virtually every other IDE/Code editor that supports CSS), which makes migration easier.

Thank you in advance.

**Comment by AradAral** [comment]
I'm willing to also create a PR for this.

**Comment by TheRealSyler** [comment]
i like that the units have a different color, that why i added it, i don't think that its possible to add an option, if there is a way to add an option i would not be against adding one.

you can change it by creating a new extension that only handles the syntax highlighting and tell vscode to not use this extension for syntax highlighting, you can get the grammar file without my changes from [here](https://github.com/atom/language-sass/tree/master/grammars).

you can copy this extension an just remove everything that has nothing to do with the syntax highlighting or you can create a new extension from scratch here is a link to get you started with creating a vscode extension: https://code.visualstudio.com/api/get-started/your-first-extension
