### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by geoidesic** [TheRealSyler/vscode-sass-indented#78]
Sorry if I'm being stupid but I can't figure out how to install this.

The readme says, "paste this into the command palette: `ext install sass-indented`". However I don't know what a `command pallette` might be. I googled it and also found it in the `help` section of vscode. However what I get is basically an autocomplete dropdown with a greater than symbol in it at the top of vs-code. If I copy and paste `ext install sass-indented` into there, nothing happens except that it says `no matching commands`.

So I'm a bit lost.

**Comment by TheRealSyler** [comment]
have a look at this article, https://code.visualstudio.com/docs/editor/extension-gallery you don't need to install extensions via the command pallet.
