### ISSUE TITLE
Color tool

### ISSUE THREAD

**Issue by JhosdryG** [TheRealSyler/vscode-sass-indented#8]
Hi! the extension is amazing, i really love it, but it would be really usefull if you add the color tool that is displayed when you put the mouse over a color code as i show in the capture below.

Hava a good day!!

![color_tool](https://user-images.githubusercontent.com/53978018/62824909-9f4f8c80-bb71-11e9-8698-2c5281027dec.PNG)

**Comment by TheRealSyler** [comment]
@JhosdryG  i already looked into this, there is the built in color picker but as far as i know you can't call it,  i might look into it again but not any time soon, if you want a color picker you can get [this](https://marketplace.visualstudio.com/items?itemName=lihui.vs-color-picker) extension.

**Comment by TheRealSyler** [comment]
@JhosdryG just want to let you know that the default color picker will be in the next Version, you have to wait a bit though, i will publish the next version in September.

**Comment by SpectralKH** [comment]
@TheRealSyler So there's actually a way for you to integrate the default color picker?

**Comment by TheRealSyler** [comment]
@SpectralKH yes, and It was really easy to implement, I just needed to read the documentation.
