### ISSUE TITLE
Warning "Empty PropertySass (Property: 0)" in v1.8.17

### ISSUE THREAD

**Issue by simpleman383** [TheRealSyler/vscode-sass-indented#89]
**Describe the bug**
When I edit any SASS file with indented syntax, I catch annoying warnings containing a message "Empty PropertySass (Property: 0)" in every line with properties. To compare, version 1.8.16 doesn't seem to reproduce such a behavior.

**To Reproduce**
1. Install Sass Extension v1.8.17
2. Create a `.sass` file in your workspace
3. Write some rules

**Expected behavior**
No warnings for a sass file with valid properties.

**Screenshots**
<img width="1440" alt="Screenshot 2021-08-18 at 11 36 26" src="https://user-images.githubusercontent.com/17178718/129866278-52989b86-6fbc-454b-8095-ea587f3e6015.png">

```
.test-class
  color: #fff
  margin: 24px
```

**Comment by TheRealSyler** [comment]
i forgot to publish the commit that disables the linter, this will be fixed in the next release.
