### ISSUE TITLE
Block comment format

### ISSUE THREAD

**Issue by aaron-bond** [TheRealSyler/vscode-sass-indented#91]
Hi, I maintain https://github.com/aaron-bond/better-comments.

I'm working on a feature at the minute where I pull the comment syntax from the loaded extensions, instead of having my own proprietary list of the comment tags.  

I've noticed that this extensions contributes block comments in the format: `/** blah blah **/` and was wondering what the reason for this is?

https://github.com/TheRealSyler/vscode-sass-indented/blob/c406990166c12a89d191c4b6f9f56515849905fd/sass.configuration.json#L4

As stated in the [Sass documentation](https://sass-lang.com/documentation/syntax/comments), the block format is `/* blah blah */`. Why the discrepancy?

Thanks!

**Comment by TheRealSyler** [comment]
im not sure, i don't remember why i changed that, i will fix it in the next version.

ive been using your extension for a couple of years, thanks for making it, small things can really improve the coding experience.

**Comment by aaron-bond** [comment]
Many thanks!
