### ISSUE TITLE
Two dollar signs when using autocomplete in vue file

### ISSUE THREAD

**Issue by Matix-Media** [TheRealSyler/vscode-sass-indented#93]
**Describe the bug**
When I try to use the autocomplete feature in a Vue file and start by typing a dollar sign ($) and click on an auto complete option, the dollar sign I wrote does not seem to get override, which leads to two dollar signs.

**To Reproduce**
Open a vue single component file, use autocomplete with variable

**Expected behavior**
only one dollar sign

**Screenshots**
If you add screen shots of code, please also paste the code as text so that i can just copy the code and reproduce the bug.
![Screenshot](https://i.imgur.com/yO869fK.gif)

**Comment by TheRealSyler** [comment]
This extension is for  .sass only, please open your issue in the vscode repo.
