### ISSUE TITLE
not format when choose format on context menu

### ISSUE THREAD

**Issue by zhangpy** [TheRealSyler/vscode-sass-indented#96]
version: v1.8.19
file name x.vue
```sass
<style lang="sass" scoped>
.my-card
  display:flex
  flex-direction: row
</style>
```

expect insert blankspace in from of "flex" text

**Comment by TheRealSyler** [comment]
it works for me, have you installed vetur?, and set it as the default formatter (you can change it by right clicking and choose format with then set default.)? and check that `vetur.format.defaultFormatter.sass` is set to `sass-formatter` and not `none`.

**Comment by TheRealSyler** [comment]
the sass extension on its own does nothing i think but im not sure, i forgot how it works exactly.
