### ISSUE TITLE
Autocomplete does not support new CSS features

### ISSUE THREAD

**Issue by gnehs** [TheRealSyler/vscode-sass-indented#98]
**Is your feature request related to a problem? Please describe.** 
Some new css features are not supported by autocomplete, such as `aspect-ratio`, `backdrop-filter` ...etc

**Describe the solution you'd like**
Please update the [`autocomplete.data.props.json`](https://github.com/TheRealSyler/vscode-sass-indented/blob/c0e394d5d1ae7afe6a7c58cd63a3f2376e003939/src/autocomplete/schemas/generatedData/autocomplete.data.props.json) 

**Describe alternatives you've considered**
It might be possible to use the CSS autocomplete data directly from VSCode?

**Additional context**
![](https://user-images.githubusercontent.com/16719720/170921486-762c1ca5-937e-47c9-9316-e1cd093663bb.jpg)

**Comment by TheRealSyler** [comment]
Thanks for letting me know, i knew this would happen someday, i don't have the time to update them right now, if you want to you can do it and i will merge the pr.

you can get the data from here https://github.com/mdn/data/tree/main/css
but you can't just merge or replace the file since the format is different and it would break the extension.
you would need to rewrite a small part of the extension or transform the data to what the extension expects.
there are some props in the extension data that are not in the mdn data, but you can probably just ignore them since they are very likely deprecated.

**Comment by Mitchman215** [comment]
I'm gonna try to tackle this and a few other updates in [my fork](https://github.com/Mitchman215/vscode-sass-indented), I'll create a pull request when it's ready to merge.

**Comment by Mitchman215** [comment]
@TheRealSyler Do you know where the data used to generate the [autocomplete.data.props.json](https://github.com/TheRealSyler/vscode-sass-indented/blob/c0e394d5d1ae7afe6a7c58cd63a3f2376e003939/src/autocomplete/schemas/generatedData/autocomplete.data.props.json) came from originally?
The [mdn data repo](https://github.com/mdn/data/tree/main/css) you linked doesn't have descriptions or listed possible values for each of the properties, information which seems to be somewhat important for displaying documentation with this extension.

**Comment by TheRealSyler** [comment]
@Mitchman215 i added the mdn data to the the data that was there before i took over the extension, i think they got it from some microsoft project but im not sure, if you really want to know you need to look at the commit history.

**Comment by TheRealSyler** [comment]
@Mitchman215 you could write a script that merges the current mdn data or maybe we need to find some other source for the data.

**Comment by TheRealSyler** [comment]
@Mitchman215 i think [this](https://github.com/TheRealSyler/vscode-sass-indented/blob/c629327bb0421d028e286dfcdaccc83a5b62a3f6/src/autocomplete/schemas/autocomplete.cssSchema.ts) is the original data.

**Comment by TheRealSyler** [comment]
i just looked at the linked issue and the new commits, it seems like you already figured it out, when your ready make a pr, ill review and merge it, thanks for spending the the time to do this.

**Comment by TheRealSyler** [comment]
Fixed by #99
